set PROJECT_NAME="gargoyle"
set KETTLE_CLIENT_DIR="C:\Users\andgrohe\Tools\pentaho\8.3GA\data-integration"


set KETTLE_HOME=%CD%
set PROJECT_DIR=%CD%\..\..\..

set PROJECT_INPUT=%PROJECT_DIR%\\%PROJECT_NAME%\\input
set PROJECT_OUTPUT=%PROJECT_DIR%\\%PROJECT_NAME%\\output
set PROJECT_CONFIG=%PROJECT_DIR%\\%PROJECT_NAME%\\config
set PROJECT_CONTENT=%PROJECT_DIR%\\%PROJECT_NAME%\\content

set OPT="-DPROJECT_NAME=%PROJECT_NAME%" "-DPROJECT_DIR=%PROJECT_DIR%" "-DPROJECT_INPUT=%PROJECT_INPUT%" "-DPROJECT_OUTPUT=%PROJECT_OUTPUT%" "-DPROJECT_CONFIG=%PROJECT_CONFIG%" "-DPROJECT_CONTENT=%PROJECT_CONTENT%"

call %KETTLE_CLIENT_DIR%\Spoon.bat %OPT% %*
