set PROJECT_NAME="gargoyle"
set KETTLE_CLIENT_DIR="C:\Users\agrohe\Tools\pentaho\7.1GA\data-integration"

set KETTLE_HOME=%CD%
set PROJECT_DIR=%CD%\..\..\..

set PROJECT_INPUT=%PROJECT_DIR%\\%PROJECT_NAME%\\input
set PROJECT_OUTPUT=%PROJECT_DIR%\\%PROJECT_NAME%\\output

set OPT=%OPT% "-DPROJECT_NAME=%PROJECT_NAME%" "-DPROJECT_DIR=%PROJECT_DIR%" "-DPROJECT_INPUT=%PROJECT_INPUT%" "-DPROJECT_OUTPUT=%PROJECT_OUTPUT%"

call %KETTLE_CLIENT_DIR%\Spoon.bat %OPT% %*
