#!/bin/sh /etc/rc.common
USE_PROCD=1
START=86
STOP=09

CONFIGURATION=mon_gargoyle

start_service() {

    # Reading config
    config_load "${CONFIGURATION}"
    local wait_sec

    config_get wait_sec mon wait_sec

    procd_open_instance

    procd_set_param command /bin/sh "/root/projects/gargoyle/scripts/bw_metrics.sh" "$wait_sec"
    procd_set_param file /etc/config/mon_gargoyle
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn \
      ${respawn_threshold:-3600} \
      ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}
